version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "email-check-backend"
s3_bucket = "email-check-backend"
s3_prefix = "email-check-backend"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
 